<?php

namespace App\Helpers;

class CountryCodes
{
    public static function getCountries()
    {
        return [
            ['code' => '+233', 'name' => 'Ghana', 'flag' => '🇬🇭'],
            ['code' => '+234', 'name' => 'Nigeria', 'flag' => '🇳🇬'],
            ['code' => '+254', 'name' => 'Kenya', 'flag' => '🇰🇪'],
            ['code' => '+256', 'name' => 'Uganda', 'flag' => '🇺🇬'],
            ['code' => '+255', 'name' => 'Tanzania', 'flag' => '🇹🇿'],
            ['code' => '+250', 'name' => 'Rwanda', 'flag' => '🇷🇼'],
            ['code' => '+251', 'name' => 'Ethiopia', 'flag' => '🇪🇹'],
            ['code' => '+220', 'name' => 'Gambia', 'flag' => '🇬🇲'],
            ['code' => '+221', 'name' => 'Senegal', 'flag' => '🇸🇳'],
            ['code' => '+225', 'name' => 'Côte d\'Ivoire', 'flag' => '🇨🇮'],
            ['code' => '+226', 'name' => 'Burkina Faso', 'flag' => '🇧🇫'],
            ['code' => '+227', 'name' => 'Niger', 'flag' => '🇳🇪'],
            ['code' => '+228', 'name' => 'Togo', 'flag' => '🇹🇬'],
            ['code' => '+229', 'name' => 'Benin', 'flag' => '🇧🇯'],
            ['code' => '+230', 'name' => 'Mauritius', 'flag' => '🇲🇺'],
            ['code' => '+231', 'name' => 'Liberia', 'flag' => '🇱🇷'],
            ['code' => '+232', 'name' => 'Sierra Leone', 'flag' => '🇸🇱'],
            ['code' => '+235', 'name' => 'Chad', 'flag' => '🇹🇩'],
            ['code' => '+236', 'name' => 'Central African Republic', 'flag' => '🇨🇫'],
            ['code' => '+237', 'name' => 'Cameroon', 'flag' => '🇨🇲'],
            ['code' => '+238', 'name' => 'Cape Verde', 'flag' => '🇨🇻'],
            ['code' => '+239', 'name' => 'São Tomé and Príncipe', 'flag' => '🇸🇹'],
            ['code' => '+240', 'name' => 'Equatorial Guinea', 'flag' => '🇬🇶'],
            ['code' => '+241', 'name' => 'Gabon', 'flag' => '🇬🇦'],
            ['code' => '+242', 'name' => 'Republic of the Congo', 'flag' => '🇨🇬'],
            ['code' => '+243', 'name' => 'Democratic Republic of the Congo', 'flag' => '🇨🇩'],
            ['code' => '+244', 'name' => 'Angola', 'flag' => '🇦🇴'],
            ['code' => '+245', 'name' => 'Guinea-Bissau', 'flag' => '🇬🇼'],
            ['code' => '+246', 'name' => 'British Indian Ocean Territory', 'flag' => '🇮🇴'],
            ['code' => '+247', 'name' => 'Ascension Island', 'flag' => '🇦🇨'],
            ['code' => '+248', 'name' => 'Seychelles', 'flag' => '🇸🇨'],
            ['code' => '+249', 'name' => 'Sudan', 'flag' => '🇸🇩'],
            ['code' => '+252', 'name' => 'Somalia', 'flag' => '🇸🇴'],
            ['code' => '+253', 'name' => 'Djibouti', 'flag' => '🇩🇯'],
            ['code' => '+257', 'name' => 'Burundi', 'flag' => '🇧🇮'],
            ['code' => '+258', 'name' => 'Mozambique', 'flag' => '🇲🇿'],
            ['code' => '+260', 'name' => 'Zambia', 'flag' => '🇿🇲'],
            ['code' => '+261', 'name' => 'Madagascar', 'flag' => '🇲🇬'],
            ['code' => '+262', 'name' => 'Réunion', 'flag' => '🇷🇪'],
            ['code' => '+263', 'name' => 'Zimbabwe', 'flag' => '🇿🇼'],
            ['code' => '+264', 'name' => 'Namibia', 'flag' => '🇳🇦'],
            ['code' => '+265', 'name' => 'Malawi', 'flag' => '🇲🇼'],
            ['code' => '+266', 'name' => 'Lesotho', 'flag' => '🇱🇸'],
            ['code' => '+267', 'name' => 'Botswana', 'flag' => '🇧🇼'],
            ['code' => '+268', 'name' => 'Eswatini', 'flag' => '🇸🇿'],
            ['code' => '+269', 'name' => 'Comoros', 'flag' => '🇰🇲'],
            ['code' => '+290', 'name' => 'Saint Helena', 'flag' => '🇸🇭'],
            ['code' => '+291', 'name' => 'Eritrea', 'flag' => '🇪🇷'],
            ['code' => '+297', 'name' => 'Aruba', 'flag' => '🇦🇼'],
            ['code' => '+298', 'name' => 'Faroe Islands', 'flag' => '🇫🇴'],
            ['code' => '+299', 'name' => 'Greenland', 'flag' => '🇬🇱'],
            ['code' => '+1', 'name' => 'United States', 'flag' => '🇺🇸'],
            ['code' => '+1', 'name' => 'Canada', 'flag' => '🇨🇦'],
            ['code' => '+44', 'name' => 'United Kingdom', 'flag' => '🇬🇧'],
            ['code' => '+33', 'name' => 'France', 'flag' => '🇫🇷'],
            ['code' => '+49', 'name' => 'Germany', 'flag' => '🇩🇪'],
            ['code' => '+39', 'name' => 'Italy', 'flag' => '🇮🇹'],
            ['code' => '+34', 'name' => 'Spain', 'flag' => '🇪🇸'],
            ['code' => '+31', 'name' => 'Netherlands', 'flag' => '🇳🇱'],
            ['code' => '+32', 'name' => 'Belgium', 'flag' => '🇧🇪'],
            ['code' => '+41', 'name' => 'Switzerland', 'flag' => '🇨🇭'],
            ['code' => '+43', 'name' => 'Austria', 'flag' => '🇦🇹'],
            ['code' => '+45', 'name' => 'Denmark', 'flag' => '🇩🇰'],
            ['code' => '+46', 'name' => 'Sweden', 'flag' => '🇸🇪'],
            ['code' => '+47', 'name' => 'Norway', 'flag' => '🇳🇴'],
            ['code' => '+358', 'name' => 'Finland', 'flag' => '🇫🇮'],
            ['code' => '+48', 'name' => 'Poland', 'flag' => '🇵🇱'],
            ['code' => '+420', 'name' => 'Czech Republic', 'flag' => '🇨🇿'],
            ['code' => '+421', 'name' => 'Slovakia', 'flag' => '🇸🇰'],
            ['code' => '+36', 'name' => 'Hungary', 'flag' => '🇭🇺'],
            ['code' => '+40', 'name' => 'Romania', 'flag' => '🇷🇴'],
            ['code' => '+359', 'name' => 'Bulgaria', 'flag' => '🇧🇬'],
            ['code' => '+385', 'name' => 'Croatia', 'flag' => '🇭🇷'],
            ['code' => '+386', 'name' => 'Slovenia', 'flag' => '🇸🇮'],
            ['code' => '+387', 'name' => 'Bosnia and Herzegovina', 'flag' => '🇧🇦'],
            ['code' => '+382', 'name' => 'Montenegro', 'flag' => '🇲🇪'],
            ['code' => '+381', 'name' => 'Serbia', 'flag' => '🇷🇸'],
            ['code' => '+389', 'name' => 'North Macedonia', 'flag' => '🇲🇰'],
            ['code' => '+355', 'name' => 'Albania', 'flag' => '🇦🇱'],
            ['code' => '+30', 'name' => 'Greece', 'flag' => '🇬🇷'],
            ['code' => '+90', 'name' => 'Turkey', 'flag' => '🇹🇷'],
            ['code' => '+7', 'name' => 'Russia', 'flag' => '🇷🇺'],
            ['code' => '+380', 'name' => 'Ukraine', 'flag' => '🇺🇦'],
            ['code' => '+375', 'name' => 'Belarus', 'flag' => '🇧🇾'],
            ['code' => '+370', 'name' => 'Lithuania', 'flag' => '🇱🇹'],
            ['code' => '+371', 'name' => 'Latvia', 'flag' => '🇱🇻'],
            ['code' => '+372', 'name' => 'Estonia', 'flag' => '🇪🇪'],
            ['code' => '+81', 'name' => 'Japan', 'flag' => '🇯🇵'],
            ['code' => '+82', 'name' => 'South Korea', 'flag' => '🇰🇷'],
            ['code' => '+86', 'name' => 'China', 'flag' => '🇨🇳'],
            ['code' => '+852', 'name' => 'Hong Kong', 'flag' => '🇭🇰'],
            ['code' => '+853', 'name' => 'Macau', 'flag' => '🇲🇴'],
            ['code' => '+886', 'name' => 'Taiwan', 'flag' => '🇹🇼'],
            ['code' => '+65', 'name' => 'Singapore', 'flag' => '🇸🇬'],
            ['code' => '+60', 'name' => 'Malaysia', 'flag' => '🇲🇾'],
            ['code' => '+66', 'name' => 'Thailand', 'flag' => '🇹🇭'],
            ['code' => '+63', 'name' => 'Philippines', 'flag' => '🇵🇭'],
            ['code' => '+62', 'name' => 'Indonesia', 'flag' => '🇮🇩'],
            ['code' => '+84', 'name' => 'Vietnam', 'flag' => '🇻🇳'],
            ['code' => '+855', 'name' => 'Cambodia', 'flag' => '🇰🇭'],
            ['code' => '+856', 'name' => 'Laos', 'flag' => '🇱🇦'],
            ['code' => '+95', 'name' => 'Myanmar', 'flag' => '🇲🇲'],
            ['code' => '+91', 'name' => 'India', 'flag' => '🇮🇳'],
            ['code' => '+92', 'name' => 'Pakistan', 'flag' => '🇵🇰'],
            ['code' => '+880', 'name' => 'Bangladesh', 'flag' => '🇧🇩'],
            ['code' => '+94', 'name' => 'Sri Lanka', 'flag' => '🇱🇰'],
            ['code' => '+977', 'name' => 'Nepal', 'flag' => '🇳🇵'],
            ['code' => '+975', 'name' => 'Bhutan', 'flag' => '🇧🇹'],
            ['code' => '+960', 'name' => 'Maldives', 'flag' => '🇲🇻'],
            ['code' => '+93', 'name' => 'Afghanistan', 'flag' => '🇦🇫'],
            ['code' => '+98', 'name' => 'Iran', 'flag' => '🇮🇷'],
            ['code' => '+964', 'name' => 'Iraq', 'flag' => '🇮🇶'],
            ['code' => '+965', 'name' => 'Kuwait', 'flag' => '🇰🇼'],
            ['code' => '+966', 'name' => 'Saudi Arabia', 'flag' => '🇸🇦'],
            ['code' => '+973', 'name' => 'Bahrain', 'flag' => '🇧🇭'],
            ['code' => '+974', 'name' => 'Qatar', 'flag' => '🇶🇦'],
            ['code' => '+971', 'name' => 'United Arab Emirates', 'flag' => '🇦🇪'],
            ['code' => '+968', 'name' => 'Oman', 'flag' => '🇴🇲'],
            ['code' => '+967', 'name' => 'Yemen', 'flag' => '🇾🇪'],
            ['code' => '+962', 'name' => 'Jordan', 'flag' => '🇯🇴'],
            ['code' => '+961', 'name' => 'Lebanon', 'flag' => '🇱🇧'],
            ['code' => '+963', 'name' => 'Syria', 'flag' => '🇸🇾'],
            ['code' => '+972', 'name' => 'Israel', 'flag' => '🇮🇱'],
            ['code' => '+970', 'name' => 'Palestine', 'flag' => '🇵🇸'],
            ['code' => '+20', 'name' => 'Egypt', 'flag' => '🇪🇬'],
            ['code' => '+218', 'name' => 'Libya', 'flag' => '🇱🇾'],
            ['code' => '+216', 'name' => 'Tunisia', 'flag' => '🇹🇳'],
            ['code' => '+213', 'name' => 'Algeria', 'flag' => '🇩🇿'],
            ['code' => '+212', 'name' => 'Morocco', 'flag' => '🇲🇦'],
            ['code' => '+222', 'name' => 'Mauritania', 'flag' => '🇲🇷'],
            ['code' => '+223', 'name' => 'Mali', 'flag' => '🇲🇱'],
            ['code' => '+224', 'name' => 'Guinea', 'flag' => '🇬🇳'],
            ['code' => '+245', 'name' => 'Guinea-Bissau', 'flag' => '🇬🇼'],
            ['code' => '+238', 'name' => 'Cape Verde', 'flag' => '🇨🇻'],
            ['code' => '+351', 'name' => 'Portugal', 'flag' => '🇵🇹'],
            ['code' => '+351', 'name' => 'Azores', 'flag' => '🇵🇹'],
            ['code' => '+351', 'name' => 'Madeira', 'flag' => '🇵🇹'],
            ['code' => '+54', 'name' => 'Argentina', 'flag' => '🇦🇷'],
            ['code' => '+55', 'name' => 'Brazil', 'flag' => '🇧🇷'],
            ['code' => '+56', 'name' => 'Chile', 'flag' => '🇨🇱'],
            ['code' => '+57', 'name' => 'Colombia', 'flag' => '🇨🇴'],
            ['code' => '+58', 'name' => 'Venezuela', 'flag' => '🇻🇪'],
            ['code' => '+51', 'name' => 'Peru', 'flag' => '🇵🇪'],
            ['code' => '+52', 'name' => 'Mexico', 'flag' => '🇲🇽'],
            ['code' => '+53', 'name' => 'Cuba', 'flag' => '🇨🇺'],
            ['code' => '+1', 'name' => 'Jamaica', 'flag' => '🇯🇲'],
            ['code' => '+1', 'name' => 'Haiti', 'flag' => '🇭🇹'],
            ['code' => '+1', 'name' => 'Dominican Republic', 'flag' => '🇩🇴'],
            ['code' => '+1', 'name' => 'Trinidad and Tobago', 'flag' => '🇹🇹'],
            ['code' => '+1', 'name' => 'Barbados', 'flag' => '🇧🇧'],
            ['code' => '+1', 'name' => 'Bahamas', 'flag' => '🇧🇸'],
            ['code' => '+61', 'name' => 'Australia', 'flag' => '🇦🇺'],
            ['code' => '+64', 'name' => 'New Zealand', 'flag' => '🇳🇿'],
            ['code' => '+679', 'name' => 'Fiji', 'flag' => '🇫🇯'],
            ['code' => '+685', 'name' => 'Samoa', 'flag' => '🇼🇸'],
            ['code' => '+676', 'name' => 'Tonga', 'flag' => '🇹🇴'],
            ['code' => '+678', 'name' => 'Vanuatu', 'flag' => '🇻🇺'],
            ['code' => '+687', 'name' => 'New Caledonia', 'flag' => '🇳🇨'],
            ['code' => '+689', 'name' => 'French Polynesia', 'flag' => '🇵🇫'],
            ['code' => '+690', 'name' => 'Tokelau', 'flag' => '🇹🇰'],
            ['code' => '+691', 'name' => 'Micronesia', 'flag' => '🇫🇲'],
            ['code' => '+692', 'name' => 'Marshall Islands', 'flag' => '🇲🇭'],
            ['code' => '+684', 'name' => 'American Samoa', 'flag' => '🇦🇸'],
            ['code' => '+683', 'name' => 'Niue', 'flag' => '🇳🇺'],
            ['code' => '+682', 'name' => 'Cook Islands', 'flag' => '🇨🇰'],
            ['code' => '+680', 'name' => 'Palau', 'flag' => '🇵🇼'],
            ['code' => '+688', 'name' => 'Tuvalu', 'flag' => '🇹🇻'],
            ['code' => '+686', 'name' => 'Kiribati', 'flag' => '🇰🇮'],
            ['code' => '+685', 'name' => 'Samoa', 'flag' => '🇼🇸'],
            ['code' => '+684', 'name' => 'American Samoa', 'flag' => '🇦🇸'],
            ['code' => '+683', 'name' => 'Niue', 'flag' => '🇳🇺'],
            ['code' => '+682', 'name' => 'Cook Islands', 'flag' => '🇨🇰'],
            ['code' => '+680', 'name' => 'Palau', 'flag' => '🇵🇼'],
            ['code' => '+688', 'name' => 'Tuvalu', 'flag' => '🇹🇻'],
            ['code' => '+686', 'name' => 'Kiribati', 'flag' => '🇰🇮'],
        ];
    }

    public static function getDefaultCountry()
    {
        return '+233'; // Ghana as default
    }
}